# -*- coding: utf-8 -*-
"""graph_embedding.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1U89MNEupOpQEvn-Us67FxgrDrDjeCq_F
"""

import os
import networkx as nx
from node2vec import Node2Vec
from gensim.models import KeyedVectors

class GraphEmbeddingAgent:
    def __init__(self, kg):
        self.kg = kg
        self.embeddings = None

    def generate_embeddings(self, file_path="graph_embeddings.wv"):
        if os.path.exists(file_path):
            print(f"Loading existing embeddings from {file_path}...")
            try:
                self.embeddings = KeyedVectors.load(file_path)
                print("✅ Embeddings loaded successfully.")
                return
            except Exception as e:
                print(f"⚠️ Failed to load existing embeddings: {e}. Regenerating...")

        print("\nEmbedding Agent is analyzing graph topology...")

        # 1. Export Neo4j Graph to NetworkX
        # FIX: Added WHERE clause to ignore nodes with missing names
        query = """
        MATCH (s)-[r]->(o)
        WHERE s.name IS NOT NULL AND o.name IS NOT NULL
        RETURN s.name AS source, o.name AS target
        """
        with self.kg.driver.session() as session:
            results = session.run(query)
            # Python-side safety filter: ensure no None values slip through
            edges = [(r["source"], r["target"]) for r in results if r["source"] and r["target"]]

        if not edges:
            print("Graph is empty or has no valid edges. Cannot generate embeddings.")
            return

        # Create NetworkX graph
        G = nx.Graph()
        G.add_edges_from(edges)

        print(f"   -> Graph loaded into memory: {len(G.nodes())} nodes, {len(G.edges())} edges.")

        # 2. Run Node2Vec
        try:
            node2vec = Node2Vec(G, dimensions=64, walk_length=30, num_walks=100, workers=1, temp_folder="/tmp", quiet=False)
            # model = node2vec.fit(window=10, min_count=1, batch_words=4)
            model = node2vec.fit(window=10, min_count=1)
            self.embeddings = model.wv
            self.embeddings.save(file_path)
            print(f"✅ Embeddings generated successfully and saved to {file_path}.")
        except Exception as e:
            print(f"Embedding generation failed: {e}")

    def find_similar_nodes(self, target_node, top_k=5):
        if not self.embeddings or target_node not in self.embeddings:
            return []
        try:
            similar = self.embeddings.most_similar(target_node, topn=top_k)
            return [{"name": name, "score": score} for name, score in similar]
        except KeyError:
            return []