# -*- coding: utf-8 -*-
"""hgenerator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JYz37_hMeXCt5FgX0k5ZzTq2QIbuiQnI
"""

import re
import json
import requests

class DrugScreeningAgent:
    def __init__(self, kg, model_name=None, OLLAMA_BASE_URL="http://localhost:11434/api/generate"):
        self.kg = kg
        self.model = model_name or OLLAMA_MODEL
        self.api_url = OLLAMA_BASE_URL

    def check_connection(self):
        try:
            requests.get(self.api_url.replace("/generate", "/tags"), timeout=20)
            return True
        except:
            return False

    def _extract_json(self, text):
        """
        Robustly extracts JSON from messy LLM output.
        Handles Markdown blocks, dictionaries, and raw lists.
        """
        # print(f"\n--- RAW LLM OUTPUT ---\n{text}\n----------------------\n")
        # 1. Clean Markdown code blocks
        text = re.sub(r'```json', '', text)
        text = re.sub(r'```', '', text)
        text = text.strip()

        result = []

        # 2. Try direct parsing
        try:
            data = json.loads(text)
            if isinstance(data, list):
                result = data
            elif isinstance(data, dict):
                # If it's a dict, look for a list inside it
                found_list = False
                for key in data:
                    if isinstance(data[key], list):
                        result = data[key]
                        found_list = True
                        break
                # If no list is found, wrap the single dictionary in a list
                if not found_list:
                    result = [data]
        except:
            pass

        # 3. Regex Search for List [...] if direct parsing failed
        if not result:
            try:
                match = re.search(r'\[.*\]', text, re.DOTALL)
                if match:
                    result = json.loads(match.group())
            except:
                pass

        # 4. BULLETPROOF FILTER: Ensure it's a list and keep ONLY dictionaries
        if isinstance(result, list):
            clean_list = [x for x in result if isinstance(x, dict)]
            return clean_list

        return []

    def generate_hypothesis(self, cancer_type, focus_gene, embedding_agent=None, method="Full"):
        print(f"\nAgent is thinking about {focus_gene} in {cancer_type} using {method} method...")

        explicit_context = []
        implicit_context = []

        # 1. Retrieve Explicit Context (GraphRAG) - Only if KG or Full is chosen
        if method in ["Full", "KG-Only"]:
            discovery_subgraph = self.kg.get_discovery_subgraph(focus_gene, cancer_type)
            if discovery_subgraph:
                for item in discovery_subgraph:
                    context = f"{item['s.name']} --[{item['type(r)']}]--> {item['o.name']}"
                    if item.get('r.confidence'):
                        context += f" (Conf: {item['r.confidence']})"
                    explicit_context.append(context)

        # 2. Retrieve Implicit Context (Embeddings) - Only if Full or Node2Vec-inclusive is chosen
        if method == "Full" and embedding_agent:
            similar_nodes = embedding_agent.find_similar_nodes(focus_gene, top_k=5)
            for node in similar_nodes:
                implicit_context.append(f"{node['name']} (Similarity Score: {node['score']:.2f})")

        # 3. Construct the Hybrid Prompt
        context_str = "\n".join(explicit_context[:25]) if explicit_context else "No direct connections in graph data found."
        implicit_str = ", ".join(implicit_context) if implicit_context else "No embedding data for this mode."

        # Special instructions for LLM-only
        if method == "LLM-only":
            knowledge_instruction = "Use your internal pre-trained medical knowledge ONLY. Ignore external graph data."
            context_str = ""
            implicit_str = ""
        else:
            knowledge_instruction = f"Strictly prioritize the provided [EXPLICIT KNOWLEDGE] and [IMPLICIT SIGNALS] for the {method} method."

        system_prompt = "You are an expert AI Biologist performing a {method} analysis."

        user_prompt = f"""
        TASK: Generate exactly 4 distinct drug combination hypotheses for {cancer_type} targeting {focus_gene}.
        METHOD USED: {method}

        {knowledge_instruction}

        [EXPLICIT KNOWLEDGE - Validated Facts from Knowledge Graph]
        {context_str}

        [IMPLICIT SIGNALS - Node2Vec Graph Embeddings]
        The following entities are mathematically similar to {focus_gene} in the graph structure.
        Use them to infer novel connections (e.g., if Drug X targets a similar gene, it might work here):
        {implicit_str}

        INSTRUCTIONS:
        1. You MUST generate a list of exactly 4 hypotheses.
        2. Use at least one "Implicit Signal" to propose a novel connection.
        3. Label "rationale_type" appropriately (e.g., "Direct Graph Evidence" if based on [EXPLICIT KNOWLEDGE], "Inferred Similarity" if based on [IMPLICIT SIGNALS], or "LLM Internal Knowledge", otherwise).
        4. In 'supporting_evidence', provide a 1-2 sentence explanation of why the evidence supports the combination, followed by an existing related URL.
        5. Each hypothesis must use the focus gene target + a different secondary target/drug.
        6. Focus on mechanisms like Synthetic Lethality or Resistance Reversal.

        HARD RULES:
        - DO NOT use numeric placeholders like [1], [2]. Use the actual URL: (https://...). Only give actual related URL, DO NOT HALLUCINATE or DO NOT link unrelated random URLs.
        - DO NOT use placeholders like [Journal Name], [Year], or [Source] etc.

        OUTPUT FORMAT (Strict JSON List of 4 items):
        [
            {{
                "id": 1,
                "method":"{method}",
                "target_disease": "{cancer_type}",
                "focus_gene": "{focus_gene}",
                "combination": "Drug A + Drug B",
                "mechanism": "...",
                "rationale_type": "<Choose one: 'Direct Graph Evidence' if based on [EXPLICIT KNOWLEDGE]; 'Inferred Similarity' if based on [IMPLICIT SIGNALS], or 'LLM Internal Knowledge', otherwise>",
                "supporting_evidence": "..."
            }},
            {{
                "id": 2,
                "method":"{method}",
                "target_disease": "{cancer_type}",
                "focus_gene": "{focus_gene}",
                "combination": "Drug A + Drug B",
                "mechanism": "...",
                "rationale_type": "<Choose one: 'Direct Graph Evidence' if based on [EXPLICIT KNOWLEDGE]; 'Inferred Similarity' if based on [IMPLICIT SIGNALS], or 'LLM Internal Knowledge', otherwise>",
                "supporting_evidence": "..."
            }},
            {{
                "id": 3,
                "method":"{method}",
                "target_disease": "{cancer_type}",
                "focus_gene": "{focus_gene}",
                "combination": "Drug A + Drug B",
                "mechanism": "...",
                "rationale_type": "<Choose one: 'Direct Graph Evidence' if based on [EXPLICIT KNOWLEDGE]; 'Inferred Similarity' if based on [IMPLICIT SIGNALS], or 'LLM Internal Knowledge', otherwise>",
                "supporting_evidence": "..."
            }},
            {{
                "id": 4,
                "method":"{method}",
                "target_disease": "{cancer_type}",
                "focus_gene": "{focus_gene}",
                "combination": "Drug A + Drug B",
                "mechanism": "...",
                "rationale_type": "<Choose one: 'Direct Graph Evidence' if based on [EXPLICIT KNOWLEDGE]; 'Inferred Similarity' if based on [IMPLICIT SIGNALS], or 'LLM Internal Knowledge', otherwise>",
                "supporting_evidence": "..."
            }}
        ]
        """

        payload = {
            "model": self.model,
            "prompt": system_prompt + "\n\n" + user_prompt,
            "stream": False,
            # "format": "json",
            "options": {
                "temperature": 0.0,
                "num_predict": 3072
            }
        }

        # 4. Retry Logic (Attempt up to 3 times)
        for attempt in range(3):
            try:
                response = requests.post(self.api_url, json=payload, timeout=300)
                if response.status_code == 200:
                    resp_text = response.json().get("response", "")
                    # print(f"      Response Snippet: {resp_text}...")
                    # print(f"      Response Length: {len(resp_text)}")

                    hypotheses = self._extract_json(resp_text)

                    if hypotheses and isinstance(hypotheses, list) and len(hypotheses) > 0:
                        print(f"      Successfully generated {len(hypotheses)} hypotheses.")
                        return hypotheses
                    else:
                        # DEBUG: Print what failed so we can see it
                        print(f"      Attempt {attempt+1} failed to parse JSON.")
                        print(f"      Raw Output Snippet: {resp_text[:1000]}...")
                else:
                    print(f"      API Error: {response.status_code}")

            except Exception as e:
                print(f"      Connection error: {e}")

        print("Failed to generate hypotheses after 3 attempts.")
        return []

print("DrugScreeningAgent class defined.")