# -*- coding: utf-8 -*-
"""hgenerator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JYz37_hMeXCt5FgX0k5ZzTq2QIbuiQnI
"""

import re
import json
import requests

class DrugScreeningAgent:
    def __init__(self, kg, model_name=None, OLLAMA_BASE_URL="http://localhost:11434/api/generate"):
        self.kg = kg
        self.model = model_name or "llama3.1"
        self.api_url = OLLAMA_BASE_URL

    def check_connection(self):
        try:
            requests.get(self.api_url.replace("/generate", "/tags"), timeout=20)
            return True
        except:
            return False

    def _extract_json(self, text):
        """
        Robustly extracts JSON from messy LLM output.
        """
        text = re.sub(r'```json', '', text)
        text = re.sub(r'```', '', text)
        text = text.strip()

        result = []

        try:
            data = json.loads(text)
            if isinstance(data, list):
                result = data
            elif isinstance(data, dict):
                found_list = False
                for key in data:
                    if isinstance(data[key], list):
                        result = data[key]
                        found_list = True
                        break
                if not found_list:
                    result = [data]
        except:
            pass

        if not result:
            try:
                match = re.search(r'\[.*\]', text, re.DOTALL)
                if match:
                    result = json.loads(match.group())
            except:
                pass

        if isinstance(result, list):
            clean_list = [x for x in result if isinstance(x, dict)]
            return clean_list

        return []

    def generate_hypothesis(self, cancer_type, focus_gene, embedding_agent=None, method="Full"):
        print(f"\nAgent is thinking about {focus_gene} in {cancer_type} using {method} method...")

        explicit_context = []
        implicit_context = []

        # 1. Retrieve Explicit Context (GraphRAG)
        if method in ["Full", "No-Node2Vec"]:
            discovery_subgraph = self.kg.get_discovery_subgraph(focus_gene, cancer_type)
            if discovery_subgraph:
                for item in discovery_subgraph:
                    # We include the source URL in the context string so the LLM has it available to cite
                    url_ref = f"[Source: {item.get('r.source', 'KG')} - {item.get('r.source_url', 'No URL')}]"
                    context = f"{item['s.name']} --[{item['type(r)']}]--> {item['o.name']} {url_ref}"
                    # if item.get('r.confidence'):
                    #     context += f" (Conf: {item['r.confidence']})"
                    explicit_context.append(context)

        # 2. Retrieve Implicit Context (Embeddings)
        if method == "Full" and embedding_agent:
            similar_nodes = embedding_agent.find_similar_nodes(focus_gene, top_k=5)
            for node in similar_nodes:
                implicit_context.append(f"{node['name']} (Similarity Score: {node['score']:.2f})")

        # 3. Construct the Hybrid Prompt
        context_str = "\n".join(explicit_context[:25]) if explicit_context else "No direct connections in graph data found."
        implicit_str = ", ".join(implicit_context) if implicit_context else "No embedding data for this mode."

        # Special instructions for LLM-only
        if method == "LLM-only":
            knowledge_instruction = "Use your internal pre-trained medical knowledge ONLY. Ignore external graph data."
            context_str = ""
            implicit_str = ""
        else:
            knowledge_instruction = f"Strictly prioritize the provided [EXPLICIT KNOWLEDGE] and [IMPLICIT SIGNALS] for the {method} method."

        system_prompt = "You are an expert AI Biologist performing a drug screening analysis."

        user_prompt = f"""
        TASK: Generate exactly 4 distinct drug combination hypotheses for {cancer_type} targeting {focus_gene}.
        METHOD USED: {method}

        {knowledge_instruction}

        [EXPLICIT KNOWLEDGE - Validated Facts from Knowledge Graph]
        {context_str}

        [IMPLICIT SIGNALS - Node2Vec Graph Embeddings]
        The following entities are mathematically similar to {focus_gene} in the graph structure.
        Use them to infer novel connections (e.g., if Drug X targets a similar gene, it might work here):
        {implicit_str}

        INSTRUCTIONS:
        1. You MUST generate a list of EXACTLY 4 hypotheses.
        2. If available, use at least one "Implicit Signal" to propose a novel connection.
        3. Mechanism: Briefly explain the biological logic (e.g., Synthetic Lethality, Resistance Reversal etc.).
        4. Rationale Type: Choose 'Direct Graph Evidence' if based on [EXPLICIT KNOWLEDGE], 'Inferred Similarity' if based on [IMPLICIT SIGNALS], or 'LLM Internal Knowledge', otherwise.
        5. Supporting Evidence:
          - Briefly explain why this works in 3-4 sentences.
          - CRITICAL: You must cite a URL ONLY if it appears in [EXPLICIT KNOWLEDGE] above.
          - If the evidence comes from your internal knowledge (LLM-only), DO NOT invent a URL. Write "General biological inference"down the evidence and explain it.
        6. Each hypothesis MUST use the focus gene target + a different secondary target/drug.

        HARD RULES FOR HALLUCINATION PREVENTION:
        - DO NOT use numeric placeholders like [1], [2].
        - DO NOT use placeholders like [Journal Name], [Year], or [Source] etc.
        - DO NOT generate fake PubMed links (e.g., pubmed.ncbi.nlm.nih.gov/12345678).
        - DO NOT make up Source Names or IDs.
        - If you do not see a "http..." link in the context provided above, DO NOT WRITE A URL.

        OUTPUT FORMAT (Strict JSON List of 4 items):
        [
            {{
                "id": 1,
                "method":"{method}",
                "target_disease": "{cancer_type}",
                "focus_gene": "{focus_gene}",
                "combination": "Drug A + Drug B",
                "mechanism": "...",
                "rationale_type": "...",
                "supporting_evidence": "Explanation... (Citation)"
            }},
            {{
                "id": 2,
                "method":"{method}",
                "target_disease": "{cancer_type}",
                "focus_gene": "{focus_gene}",
                "combination": "Drug A + Drug B",
                "mechanism": "...",
                "rationale_type": "...",
                "supporting_evidence": "Explanation... (Citation)"
            }},
            {{
                "id": 3,
                "method":"{method}",
                "target_disease": "{cancer_type}",
                "focus_gene": "{focus_gene}",
                "combination": "Drug A + Drug B",
                "mechanism": "...",
                "rationale_type": "...",
                "supporting_evidence": "Explanation... (Citation)"
            }},
            {{
                "id": 4,
                "method":"{method}",
                "target_disease": "{cancer_type}",
                "focus_gene": "{focus_gene}",
                "combination": "Drug A + Drug B",
                "mechanism": "...",
                "rationale_type": "...",
                "supporting_evidence": "Explanation... (Citation)"
            }}
        ]
        """

        payload = {
            "model": self.model,
            "prompt": system_prompt + "\n\n" + user_prompt,
            "stream": False,
            # "format": "json",
            "options": {
                "temperature": 0.0,
                "num_predict": 3072
            }
        }

        for attempt in range(3):
            try:
                response = requests.post(self.api_url, json=payload, timeout=300)
                if response.status_code == 200:
                    resp_text = response.json().get("response", "")
                    hypotheses = self._extract_json(resp_text)
                    if hypotheses and isinstance(hypotheses, list) and len(hypotheses) > 0:
                        print(f"      Successfully generated {len(hypotheses)} hypotheses.")
                        return hypotheses
                    else:
                        print(f"      Attempt {attempt+1} failed to parse JSON.")
                        # print(f"      Raw Output Snippet: {resp_text[:1000]}...")
                else:
                    print(f"      API Error: {response.status_code}")

            except Exception as e:
                print(f"      Connection error: {e}")

        print("Failed to generate hypotheses after 3 attempts.")
        return []