# -*- coding: utf-8 -*-
"""hranker.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nde1Re00UNc8xJ5bOYz0fYM93gj6Imot
"""

class RankingAgent:
    def __init__(self, kg):
        self.kg = kg

    def calculate_graph_support(self, hypothesis):
        """
        Queries the graph to see if the genes/drugs involved have VALIDATED or EXPERIMENTAL edges.
        """
        skip_words = {'a', 'an', 'and', 'the', 'by', 'of', 'from', 'on', 'in', 'to', 'with', 'activator', 'inhibitor', 'inducer', '(e.g.,'}
        keywords = hypothesis.get('combination', '').replace("+", " ").split()
        keywords = [k.strip() for k in keywords if len(k) > 2 and k.lower() not in skip_words]

        score = 0.0
        focus_gene = hypothesis.get('focus_gene', '')
        cancer_type = hypothesis.get('target_disease', '')

        query = """
        MATCH path = (d:Drug)-[r*1..2]-(target)
        WHERE toLower(d.name) IN $kws
          AND (toLower(target.name) CONTAINS toLower($gene)
              OR toLower(target.name) CONTAINS toLower($disease))
        UNWIND relationships(path) AS rel
        RETURN type(rel) AS rel_type, rel.layer AS layer //, length(path) AS hop_count, rel.source as source
        LIMIT 50
        """
        with self.kg.driver.session() as session:
            kws_lower = [k.lower() for k in keywords]
            results = session.run(query, kws=kws_lower, gene=focus_gene, disease=cancer_type).data()

            for res in results:
                if res['layer'] == 'VALIDATED':
                    score += 2.0
                elif res['layer'] == 'EXPERIMENTAL':
                    score += 1
                else:
                    score += 0.6

        return min(score, 10.0)

    def rank(self, hypotheses):
        print("\nRanking Agent is sorting hypotheses...")

        for h in hypotheses:
            ai_score = float(h.get("safety_score", 0))
            graph_score = self.calculate_graph_support(h)
            h["graph_evidence_score"] = graph_score
            h["ranking_score"] = round((ai_score + graph_score) / 2, 2)

            method = h["method"]

            if method == "LLM-only":
                h['rationale_type'] = "LLM Internal Knowledge"
            elif method == "KG-Only" or graph_score >= 5:
                h['rationale_type'] = "Direct Graph Evidence"
            elif "Inferred" in h.get('rationale_type', '') or graph_score < 5:
                 h['rationale_type'] = "Inferred Similarity (Embeddings)"

            ne_hits = h.get('ne_hits', 0)
            nc_hits = h.get('nc_hits', 0)

            if h["ranking_score"] >= 8.0:
                calculated_verdict = "Proceed"
            elif ne_hits == 0 or nc_hits == 0:
                if ai_score >= 6.0 or graph_score >= 6.0:
                    calculated_verdict = "Proceed (Novel - Caution)"
                else:
                    calculated_verdict = "Caution (Novel - Low Evidence)"
            elif h["ranking_score"] >= 5.0:
                calculated_verdict = "Caution"
            else:
                calculated_verdict = "Reject"

            h['verdict'] = calculated_verdict

        hypotheses_sorted = sorted(hypotheses, key=lambda x: x["ranking_score"], reverse=True)

        return hypotheses_sorted