# -*- coding: utf-8 -*-
"""hvalidator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1R3PBTXT4ETSKl2N8zjiFoBEwJVRt0sE9
"""

import json
import requests
from Bio import Entrez

OLLAMA_MODEL = "llama3.1"

class ValidationAgent:
    def __init__(self, kg, model_name=None, OLLAMA_BASE_URL="http://localhost:11434/api/generate"):
        self.kg = kg
        self.model = model_name or OLLAMA_MODEL
        self.api_url = OLLAMA_BASE_URL
        self.email = globals().get("Entrez.email", "basak.suvinava@mh-hannover.de")
        Entrez.email = self.email

    def check_combination_evidence(self, drugs, cancer_type):
        """
        Performs a 'Just-in-Time' PubMed search for the specific combination.
        """
        if len(drugs) < 2:
            return {"status": "Single Agent", "urls": [], "note": "Single drug"}

        # Construct Query: "Drug A" AND "Drug B"
        clean_drugs = [f'"{d}"' for d in drugs]
        query_ne = f"({' AND '.join(clean_drugs)})"                             # Novelty-Exact (NE)
        query_nc = f"({' AND '.join(clean_drugs)}) AND {cancer_type}"           # Novelty-in-Context (NC)

        ne_hits, ne_ids = self._get_pubmed_count(query_ne)
        nc_hits, nc_ids = self._get_pubmed_count(query_nc)

        found_urls = []

        if ne_hits > 0 or nc_hits > 0:
            if ne_hits:
                for pmid in ne_ids:
                    found_urls.append(f"https://pubmed.ncbi.nlm.nih.gov/{pmid}/")
            if nc_hits:
                for pmid in nc_ids:
                    found_urls.append(f"https://pubmed.ncbi.nlm.nih.gov/{pmid}/")

            return {
                "status": "Validated (Literature Exists)",
                "urls": found_urls,
                "ne_hits": ne_hits,
                "nc_hits": nc_hits,
                "is_novel_exact": ne_hits == 0,
                "is_novel_context": nc_hits == 0,
            }

        return {
            "status": "Inferred (Novel Combination)",
            "urls": [],
            "ne_hits": ne_hits,
            "nc_hits": nc_hits,
            "is_novel_exact": ne_hits == 0,
            "is_novel_context": nc_hits == 0,
        }

    def _get_pubmed_count(self, query):
        try:
            handle = Entrez.esearch(db="pubmed", term=query, retmax=5)
            record = Entrez.read(handle)
            return int(record["Count"]), record["IdList"]
        except: return 0, []

    def validate_batch(self, hypotheses_list):
        print("\nValidation Agent is reviewing candidates...")
        validated_results = []

        if not hypotheses_list:
            print("   No hypotheses to validate.")
            return []

        for hypo in hypotheses_list:
            if not isinstance(hypo, dict):
                print(f"   Skipping invalid data format: {hypo}")
                continue

            print(f"   -> Reviewing Hypothesis {hypo.get('id', '?')}: {hypo.get('combination', 'Unknown')}")

            combo_str = hypo.get('combination', '')
            # drugs = [d.strip() for d in combo_str.replace("+", ",").split(",") if d.strip()]
            drugs = [d.strip().split()[0] for d in combo_str.replace("+", ",").split(",") if d.strip()]

            focus_gene = hypo.get('focus_gene')
            cancer_type = hypo.get('target_disease')

            combo_check = self.check_combination_evidence(drugs, cancer_type)

            # Retrieve Individual Safety Data and URLs from Graph
            safety_context = []
            hypo['civic_urls'] = []
            hypo['chembl_urls'] = []
            hypo['trial_urls'] = []
            hypo['reactome_urls'] = []

            for drug in drugs:
                # Optimized query to find all relationships (r) connected to the drug (d)
                validated_facts = self.kg.get_validated_subgraph(
                    entities=[drug],
                    focus_gene=focus_gene,
                    cancer_type=cancer_type
                )
                fact_entries = []
                for record in validated_facts:
                    source = record.get('r.source', 'Unknown')
                    rel = record.get('type(r)', 'interacts with')
                    obj = record.get('o.name', 'Unknown')
                    fact_entries.append(f"({source} Fact): {drug} {rel} {obj}")

                query = """
                MATCH (d:Drug)
                WHERE toLower(d.name) CONTAINS toLower($name)

                // Step 1: Side Effects
                OPTIONAL MATCH (d)-[:CAUSES_SIDE_EFFECT]->(se:SideEffect)
                WITH d, collect(DISTINCT se.name)[..25] AS side_effects

                // Step 2: Identify Disease Context
                OPTIONAL MATCH (dis:Disease)
                WHERE toLower(dis.name) CONTAINS toLower($cancer_type)
                  OR toLower($cancer_type) CONTAINS toLower(dis.name)

                OPTIONAL MATCH (g:Gene)
                WHERE toLower(g.name) CONTAINS toLower($focus_gene)
                  OR toLower($focus_gene) CONTAINS toLower(g.name)

                WITH d, side_effects, dis, g
                OPTIONAL MATCH p_civic = (d)-[:TREATS|TARGETS|ASSOCIATED_WITH*1..2]-(dis)
                WHERE all(rel IN relationships(p_civic) WHERE rel.source = "CIViC")

                WITH d, side_effects, dis, g, collect(DISTINCT p_civic) AS civic_paths
                OPTIONAL MATCH (d)-[r_chembl_p:REACHED_PHASE]-(:Phase) WHERE r_chembl_p.source = "ChEMBL"
                OPTIONAL MATCH (d)-[r_chembl_t:TARGETS]-(g) WHERE r_chembl_t.source = "ChEMBL"

                WITH d, side_effects, dis, g, civic_paths, r_chembl_p, r_chembl_t
                OPTIONAL MATCH (t:ClinicalTrial)-[r1:TESTS_DRUG]-(d) WHERE r1.source = "ClinicalTrials.gov"
                OPTIONAL MATCH (t)-[r2:TREATS_CONDITION]-(dis) WHERE r2.source = "ClinicalTrials.gov"
                OPTIONAL MATCH (t)-[r3:INVESTIGATES_TARGET]-(g) WHERE r3.source = "ClinicalTrials.gov"

                // Final return with aggregation
                RETURN d.name, d.max_phase, d.is_withdrawn, side_effects,
                    [path IN civic_paths | [rel IN relationships(path) | rel.source_url][0]][..3] AS civic_urls,
                    (collect(DISTINCT r_chembl_p.source_url) + collect(DISTINCT r_chembl_t.source_url))[..3] AS chembl_urls,
                    (collect(DISTINCT r1.source_url) + collect(DISTINCT r2.source_url) + collect(DISTINCT r3.source_url))[..3] AS trial_urls
                """
                with self.kg.driver.session() as session:
                    res = session.run(query, name=drug, focus_gene=focus_gene, cancer_type=cancer_type).data()
                    if res:
                        phase = res[0].get('d.max_phase', 0)
                        withdrawn = res[0].get('d.is_withdrawn', False)

                        hypo['civic_urls'].extend(res[0].get('civic_urls', []))
                        hypo['chembl_urls'].extend(res[0].get('chembl_urls', []))
                        hypo['trial_urls'].extend(res[0].get('trial_urls', []))
                        hypo['reactome_urls'].extend(res[0].get('reactome_urls', []))

                        status = "FDA Approved" if phase == 4 else f"Phase {phase}"
                        tox_warning = "⚠️ WITHDRAWN" if withdrawn else "Active"
                        side_effects = res[0].get('side_effects', [])
                        se_str = f" | Common Side Effects: {', '.join(side_effects)}" if side_effects else ""
                        facts_str = f" | Biological Facts: {'; '.join(fact_entries)}" if fact_entries else ""

                        drug_name = res[0].get('d.name', drug)
                        safety_context.append(f"DRUG: {drug_name} | STATUS: {status} | OTHER FACTS: {tox_warning}, {se_str}, {facts_str}")

            # Deduplicate the URLs after both drugs have been processed
            hypo['civic_urls'] = list(set(hypo['civic_urls']))
            hypo['chembl_urls'] = list(set(hypo['chembl_urls']))
            hypo['trial_urls'] = list(set(hypo['trial_urls']))
            hypo['reactome_urls'] = list(set(hypo['reactome_urls']))

            safety_str = "\n".join(safety_context) if safety_context else "No specific safety or fact-based data found in the knowledge graph."

            # 3. Prompt for Verdict
            system_prompt = "You are a clinical auditor. You need to validate the drug combination hypothesis for the given disease and evaluate its propsect."
            user_prompt = f"""
            HYPOTHESIS: {combo_str}
            DISEASE: {cancer_type}

            MECHANISM: {hypo.get('mechanism', 'N/A')}

            [EVIDENCE CHECK]
            Status: {combo_check['status']}

            [INDIVIDUAL DRUG PROFILES]
            {safety_str}

            TASK:
            1. Assign a Safety Score (1-10). If a drug is "WITHDRAWN", score must be < 3.
            2. Evaluate Plausibility (Biological sense) (Low/Moderate/High) with detailed reasoning.
            3. Assess Combination Toxicity Risk (Low/Moderate/High) with proper reasoning based on the [EVIDENCE CHECK] and [INDIVIDUAL_DRUG_PROFILES]. If Evidence Status is "Inferred", then you MUST predict the toxicity and state "Predicted based on individual profiles" and explain your reasoning for the overlapping toxicities.
            4. Write a short critique.
            5. Provide supporting evidences: For every claim, explain the finding and immediately follow it with the relevant URL in brackets.

            HARD RULES:
            - DO NOT use numeric placeholders like [1], [2]. Use the actual URL: (https://...). Only give actual related URL, DO NOT HALLUCINATE or DO NOT link unrelated random URLs.
            - If a specific journal name is not in the context, do not invent one. DO NOT use placeholders like [Journal Name], [Year], or [Source].
            - If no direct study exists, explicitly state: "Mechanism inferred from drug properties; no direct clinical study found for this specific combination."

            OUTPUT FORMAT (JSON):
            {{
                "safety_score": 8,
                "plausibility": "(Low/Moderate/High). Reason: ...",
                "combination_toxicity_risk": "(Low/Moderate/High). Reason: ...",
                "critique": "...",
                "supporting_evidence": "Detailed explanation with URL citations..."
            }}
            """
            payload = {
                "model": self.model,
                "prompt": system_prompt + "\n\n" + user_prompt,
                "stream": False,
                "format": "json",
                "options": {"temperature": 0.0}
            }

            try:
                r = requests.post(self.api_url, json=payload, timeout=300)
                # Handle potential JSON errors from the Validation LLM as well
                try:
                    val_data = json.loads(r.json().get("response", "{}"))
                except:
                    # Fallback if validation LLM returns bad JSON
                    val_data = {"verdict": "Error", "safety_score": 0, "critique": "Validation agent failed to output JSON."}

                hypo.update(val_data)

                hypo['source_urls'] = list(dict.fromkeys(combo_check['urls']))
                hypo['evidence_status'] = combo_check['status']
                hypo['ne_hits'] = combo_check['ne_hits']
                hypo['nc_hits'] = combo_check['nc_hits']
                hypo['is_novel_exact'] = combo_check['is_novel_exact']
                hypo['is_novel_context'] = combo_check['is_novel_context']

                validated_results.append(hypo)
            except Exception as e:
                print(f"Validation Error: {e}")
                hypo.update({"verdict": "Error", "safety_score": 0})
                validated_results.append(hypo)

        return validated_results

print("ValidationAgent class defined.")

