# -*- coding: utf-8 -*-
"""main.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ccxd0_NbDI97nQ9Rnd0nyJOddle-fL3c
"""

!pip install reactome2py civicpy chembl_webresource_client rdkit neo4j biopython spacy scispacy -q
!pip install https://s3-us-west-2.amazonaws.com/ai2-s2-scispacy/releases/v0.5.4/en_ner_bionlp13cg_md-0.5.4.tar.gz -q
!pip install thefuzz sentence-transformers node2vec -q

import io
import os
import re
import sys
import ast
import time
import json
import spacy
import scispacy
import zipfile
import requests
import subprocess
import urllib.parse
import pandas as pd
import networkx as nx
from rdkit import Chem
from Bio import Entrez
from civicpy import civic
from thefuzz import process
from node2vec import Node2Vec
from datetime import datetime
from neo4j import GraphDatabase
from reactome2py import analysis
from collections import defaultdict
from gensim.models import KeyedVectors
from google.colab import drive, userdata
from scispacy.linking import EntityLinker
from sentence_transformers import SentenceTransformer, util
from chembl_webresource_client.new_client import new_client

drive.mount('/content/drive', force_remount=True)
folder_path = '/content/drive/MyDrive/Colab Notebooks/AIcoS/FINAL'

if folder_path not in sys.path:
    sys.path.append(folder_path)

# import importlib
# import build_kg
# importlib.reload(build_kg)

from build_kg import KnowledgeGraph
from nlp_processor import LiteratureProcessor
from fetch_data_util import (
    fetch_reactome_pathways,
    fetch_civic_database,
    fetch_gdc_data,
    fetch_clinical_trials,
    fetch_gene_metadata,
    fetch_chembl_data,
    fetch_string_interactions,
    fetch_synlethdb_local,
    get_depmap_direct_links,
    fetch_depmap_essentials,
    fetch_sider_data,
    fetch_drug_data_integrated,
)
from graph_embedding import GraphEmbeddingAgent
from hgenerator import DrugScreeningAgent
from hvalidator import ValidationAgent
from hranker import RankingAgent
from synergycheck import SynergyChecker
from metrics import calculate_ranking_metrics

pd.set_option('display.max_columns', None)

!apt-get install -y zstd                                        # Install the missing tool (zstd) first!
!curl -fsSL https://ollama.com/install.sh | sh                  # Install Ollama
process = subprocess.Popen("ollama serve", shell=True)          # Start Ollama as a background process
print("Starting Ollama server...")                              # Give it a few seconds to start up
time.sleep(5)
!pip install ollama                                             # Install the Python library to talk to it
print("Downloading Llama 3.1...")
!ollama pull llama3.1                                           # Pull Llama 3.1

Entrez.email = 'basak.suvinava@mh-hannover.de'

GENES_OF_INTEREST = [
    "MYC", "EGFR", "CCNE1", "MDM2", "PIK3CA", "PTEN", "TP53", "KRAS",
    "CHK1", "PARP1", "WEE1", "ATR", "AURKA", "CDK4", "CDK6", "ATM"
]

PROJECTS_OF_INTEREST = {
    "TCGA-GBM": {"full_name": "Glioblastoma Multiforme", "broad_disease": "Brain"},
    "TCGA-LGG": {"full_name": "Brain Lower Grade Glioma", "broad_disease": "Brain"},
    "TCGA-BRCA": {"full_name": "Breast Invasive Carcinoma", "broad_disease": "Breast"},
    "TCGA-LUAD": {"full_name": "Lung Adenocarcinoma", "broad_disease": "Lung"},
    "TCGA-LUSC": {"full_name": "Lung Squamous Cell Carcinoma", "broad_disease": "Lung"},
    "TCGA-COAD": {"full_name": "Colon Adenocarcinoma", "broad_disease": "Colorectal"},
    "TCGA-READ": {"full_name": "Rectum Adenocarcinoma", "broad_disease": "Colorectal"},
    "TCGA-SKCM": {"full_name": "Skin Cutaneous Melanoma", "broad_disease": "Skin"},
    "TCGA-HNSC": {"full_name": "Head and Neck Squamous Cell Carcinoma", "broad_disease": "Head and Neck"},
    "TCGA-KIRC": {"full_name": "Kidney Renal Clear Cell Carcinoma", "broad_disease": "Kidney"},
    "TCGA-LIHC": {"full_name": "Liver Hepatocellular Carcinoma", "broad_disease": "Liver"},
    "TCGA-OV": {"full_name": "Ovarian Serous Cystadenocarcinoma", "broad_disease": "Ovary"},
    "TCGA-PAAD": {"full_name": "Pancreatic Adenocarcinoma", "broad_disease": "Pancreas"},
    "TCGA-PRAD": {"full_name": "Prostate Adenocarcinoma", "broad_disease": "Prostate"},
    "TCGA-BLCA": {"full_name": "Bladder Urothelial Carcinoma", "broad_disease": "Bladder"},
    "TCGA-STAD": {"full_name": "Stomach Adenocarcinoma", "broad_disease": "Stomach"}
}

NEO4J_URI = userdata.get('NEO4J_URI')
NEO4J_USER = userdata.get('NEO4J_USER')
NEO4J_PASSWORD = userdata.get('NEO4J_PASSWORD')

SAVE_PATH = "/content/drive/MyDrive/Colab Notebooks/AIcoS/FINAL/data_cache/"
os.makedirs(SAVE_PATH, exist_ok=True)
REPORT_DIR = "/content/drive/MyDrive/Colab Notebooks/AIcoS/FINAL/reports/"
os.makedirs(REPORT_DIR, exist_ok=True)

OLLAMA_MODEL = "llama3.1" # or "tinyllama", "phi3", "gemma2:2b", "qwen2.5:3b"
OLLAMA_BASE_URL = "http://localhost:11434/api/generate"

def build_full_graph():
    def get_data(name, fetch_func, *args):
        file_path = f"{SAVE_PATH}{name}.csv"
        if os.path.exists(file_path):
            print(f"Loading {name} from Drive...")
            df = pd.read_csv(file_path)
            df = df.fillna('N/A')
            return df
        else:
            print(f"Fetching fresh {name} data (this will take time)...")
            df = fetch_func(*args)
            df = df.fillna('N/A')
            df.to_csv(file_path, index=False)
            return df

    try:
        # Fetch all the data from the public databases
        print("Starting to fetch data from databases...")
        # df_civic = fetch_civic_database(GENES_OF_INTEREST)
        # df_tcga_gdc = fetch_gdc_data(GENES_OF_INTEREST, PROJECTS_OF_INTEREST)
        # df_depmap_data = fetch_depmap_essentials(GENES_OF_INTEREST)

        # df_reactome = fetch_reactome_pathways(GENES_OF_INTEREST)
        # df_clinical_trial = fetch_clinical_trials(GENES_OF_INTEREST)
        # df_chembl = fetch_chembl_data(GENES_OF_INTEREST)

        # df_string = fetch_string_interactions(GENES_OF_INTEREST)
        # df_synleth = fetch_synlethdb_local(GENES_OF_INTEREST)

        # df_gene_meta = fetch_gene_metadata(GENES_OF_INTEREST)
        # df_drugs = fetch_drug_data_integrated(GENES_OF_INTEREST)

        df_civic = get_data("civic", fetch_civic_database, GENES_OF_INTEREST)
        df_tcga_gdc = get_data("tcga-gdc", fetch_gdc_data, GENES_OF_INTEREST, PROJECTS_OF_INTEREST)
        df_depmap_data = get_data("depmap", fetch_depmap_essentials, GENES_OF_INTEREST)

        df_reactome = get_data("reactome", fetch_reactome_pathways, GENES_OF_INTEREST)
        df_clinical_trial = get_data("clinical-trial", fetch_clinical_trials, GENES_OF_INTEREST)
        df_chembl = get_data("chembl", fetch_chembl_data, GENES_OF_INTEREST)

        df_string = get_data("string", fetch_string_interactions, GENES_OF_INTEREST)
        df_synleth = get_data("synleth", fetch_synlethdb_local, GENES_OF_INTEREST)

        df_gene_meta = get_data("gene-meta", fetch_gene_metadata, GENES_OF_INTEREST)
        df_drugs = get_data("drugs", fetch_drug_data_integrated, GENES_OF_INTEREST)

        kg.wipe_database()
        kg.create_constraints()

        # Running all the load commands to integrate data into the graph
        print("Starting to load data into the graph...")
        kg.load_civic_data(df_civic)
        kg.load_gdc_data(df_tcga_gdc)
        kg.load_depmap_data(df_depmap_data)

        kg.load_reactome_pathways(df_reactome)
        kg.load_clinical_trials(df_clinical_trial)
        kg.load_chembl_data(df_chembl)

        kg.load_string_interactions(df_string)
        kg.load_synleth_smart_mapping(df_synleth)

        kg.load_gene_metadata(df_gene_meta)
        kg.load_drug_metadata_consensus(df_drugs)

        kg.enrich_drugs_with_sider()

        # print("Fetching dynamic ontology from Neo4j...")
        # CURRENT_NODES, CURRENT_RELATIONS = kg.get_ontology_context(target_labels=['Gene', 'Drug', 'Disease'])

        # print(f"Found {len(CURRENT_RELATIONS)} relation types and nodes for {list(CURRENT_NODES.keys())}")

        # processor = LiteratureProcessor(existing_nodes=CURRENT_NODES, existing_relations=CURRENT_RELATIONS, email=Entrez.email)
        # diseases = [p["full_name"] for p in PROJECTS_OF_INTEREST.values()]
        # genes_to_search = GENES_OF_INTEREST

        # total_papers = 0
        # all_triples = []

        # for gene in genes_to_search:
        #     papers = processor.fetch_papers(gene, diseases, max_results=5)
        #     if not papers:
        #         print(f"No papers found for {gene}. Skipping...")
        #         continue

        #     triples = processor.extract_triples(papers)
        #     total_papers += len(papers)
        #     all_triples.extend(triples)

        # print(f"✅ Literature Mining Complete: Processed {total_papers} abstracts, extracted {len(all_triples)} edges.")

        # kg.load_literature_triples(all_triples)
        # print("✅ Knowledge graph fully built from all databases and literature triples.")

    except Exception as e:
        print(f"Error Occured in knowledge graph building phase: {e}")
        return None

def embed_graph(kg, embedder=None):
    try:
        print("\n--- Database Statistics ---")
        with kg.driver.session() as session:
            count = session.run("MATCH (n) RETURN count(n) as c").single()["c"]
            print(f"Total Nodes in Graph: {count}")

            # Optional: Breakdown by label
            labels = session.run("MATCH (n) RETURN distinct labels(n) as l, count(n) as c")
            for record in labels:
                print(f"   - {record['l']}: {record['c']}")

            # Optional: Check connectivity
            iso = session.run("MATCH (n) WHERE NOT (n)--() RETURN count(n) as c").single()["c"]
            if iso > 0: print(f"Warning: {iso} isolated nodes found (Connectivity Issue).")
            else: print(f"Graph Connectivity: Excellent (0 isolated nodes).")


        if embedder:
            EMBEDDING_FILE = os.path.join(SAVE_PATH, "graph_embeddings.wv")
            print("\n--- Learning Latent Representations ---")
            embedder.generate_embeddings(file_path=EMBEDDING_FILE)

    except Exception as e:
        print(f"Error Occured in graph embedding phase: {e}")
        return None

def run_full_experiment(kg, INPUT_GENE, INPUT_DISEASE, method="Full", num_lit=50):
    model_name = "llama3.1"
    generator = DrugScreeningAgent(kg, model_name=model_name)
    validator = ValidationAgent(kg, model_name=model_name)
    ranker = RankingAgent(kg)

    try:
        # Searching PubMed for INPUT_GENE and INPUT_DISEASE
        if method in ["Full", "No-Node2Vec"]:
            print("Fetching dynamic ontology from Neo4j...")
            CURRENT_NODES, CURRENT_RELATIONS = kg.get_ontology_context(target_labels=['Gene', 'Drug', 'Disease'])
            nlp = LiteratureProcessor(existing_nodes=CURRENT_NODES, existing_relations=CURRENT_RELATIONS, email=Entrez.email)

            papers = nlp.fetch_papers(INPUT_GENE, INPUT_DISEASE, max_results=num_lit)
            if not papers:
                print(f"No papers found in PubMed for given {INPUT_GENE} and {INPUT_DISEASE}...")

            triples = nlp.extract_triples(papers)
            print(f"✅ Literature Mining Complete: Processed {len(papers)} abstracts, extracted {len(triples)} relationship triples.")
            kg.load_literature_triples(triples)

        embedder=None
        # Embedding Generation
        if method == "Full":
            embedder = GraphEmbeddingAgent(kg)
            embed_graph(kg, embedder)

        # Hypotheses Generation
        print("\n--- Generating Hypotheses ---")
        hypotheses_list = generator.generate_hypothesis(INPUT_DISEASE, INPUT_GENE, embedding_agent=embedder, method=method)
        if not hypotheses_list:
            print("No hypotheses generated.")
            return None

        # Hypotheses Validation
        print("\n--- Validating Hypotheses ---")
        validated_list = validator.validate_batch(hypotheses_list)

        # Hypotheses Ranking
        print("\n--- Ranking Hypotheses ---")
        final_ranked_list = ranker.rank(validated_list)

        return final_ranked_list

    except Exception as e:
        print(f"Error Occured in hypotheses handling phase: {e}")
        return None

if __name__ == "__main__":
    def save_report_json(results, REPORT_DIR = "/content/drive/MyDrive/Colab Notebooks/AIcoS/FINAL/reports/"):
        if not os.path.exists(REPORT_DIR):
            os.makedirs(REPORT_DIR)

        filename = os.path.join(REPORT_DIR, f"final_report_{datetime.now().strftime('%Y%m%d_%H%M%S')}.json")
        with open(filename, 'w') as f:
            json.dump(results, f, indent=4)
        print(f"Report saved to {filename}")

    kg = KnowledgeGraph(NEO4J_URI, NEO4J_USER, NEO4J_PASSWORD)

    with kg.driver.session() as session:
        node_count = session.run("MATCH (n) RETURN count(n) as c").single()["c"]

    if node_count == 0:
        print("Graph is empty. Starting full build...")
        build_full_graph()
    else:
        print(f"Verified: Graph already contains {node_count} nodes. Skipping initial load.")


    INPUT_GENE = "ATM"
    INPUT_DISEASE = "Lung Adenocarcinoma"
    CHOSEN_METHOD = "Full" # Options: "Full", "No-Node2Vec", "LLM-only"
    LIT_TO_FETCH = 50

    # Hypothesis generate + validate + rank
    results = run_full_experiment(kg, INPUT_GENE, INPUT_DISEASE, method=CHOSEN_METHOD, num_lit=LIT_TO_FETCH)

    if results:
        mrr_score, ndcg_score = calculate_ranking_metrics(results, k=3)

        print("\n" + "="*80)
        print("CoDHy FINAL REPORT")
        print("="*80)
        print(f"\nCancer Type: {INPUT_DISEASE}")
        print(f"Gene in context: {INPUT_GENE}")
        print(f"Generation Method: {CHOSEN_METHOD}")
        print("\n" + "-"*50)

        print(f"MRR (First Valid Hit): {mrr_score:.4f}")
        print(f"nDCG@3 (Ranking Quality): {ndcg_score:.4f}")
        print("\n" + "-"*50)

        synergy = SynergyChecker(kg, SAVE_PATH)

        for i, h in enumerate(results, 1):
            combo_str = h.get('combination', '')

            drugs = [d.strip() for d in combo_str.split("+") if d.strip()]
            drug1, drug2 = drugs[:2]
            synergy_summary = synergy.check_drugcomb_synergy(drug1, drug2)
            h['synergy'] = synergy_summary if synergy_summary else "No direct data in DrugComb database for this drug combination."

            print(f"\nRANK {i}: {combo_str}")
            print(f"   • Rationale: {h.get('rationale_type', 'N/A')}")
            print(f"   • Mechanism: {h.get('mechanism')}")
            print(f"   • Verdict: {h.get('verdict', 'N/A')}")

            # Score Breakdown
            print(f"   • SCORES:")
            print(f"     - Composite: {h.get('ranking_score')}/10")
            print(f"     - Safety (AI): {h.get('safety_score')}/10")
            print(f"     - Evidence (Graph): {h.get('graph_evidence_score'):.1f}/10.0")

            # Critique Details
            print(f"   • CRITIQUE:")
            print(f"     - Novelty-Exact: {h.get('is_novel_exact', 'N/A')} with {h.get('ne_hits', 0)} hits")
            print(f"     - Novelty-in-Context: {h.get('is_novel_context', 'N/A')} with {h.get('nc_hits', 0)} hits")
            print(f"     - Plausibility: {h.get('plausibility', 'N/A')}")
            print(f"     - Synergy: {h['synergy']}")
            print(f"     - Combination Toxicity: {h.get('combination_toxicity_risk', 'N/A')}")
            print(f"     - Remarks: {h.get('critique')}")
            print(f"     - Supporting evidence: {h.get('supporting_evidence')}")

            # We collect ALL source_urls from the hypothesis data
            print(f"   • EVIDENCE SOURCES:")

            all_sources = list(set(h.get('source_urls', [])))
            pubmed_links = [url for url in all_sources if "pubmed.ncbi.nlm.nih.gov" in url]

            print(f"     - [Clinical & Knowledge Databases]:")
            for db_key in ['civic_urls', 'chembl_urls', 'trial_urls', 'reactome_urls']:
                # label = db_key.split('_')[0].upper()
                urls = h.get(db_key, [])
                # print(f"     - [{label} DATABASE]:")
                if urls:
                    for url in urls[:3]:
                        print(f"       • {url}")
                else:
                    print(f"       • No direct records found.")

            print(f"     - [Research Literature - PubMed]:")
            if pubmed_links:
                for url in pubmed_links[:4]:
                    print(f"       • {url}")
            else:
                print(f"       • No specific combination literature found.")

        print("\n" + "="*80)
        save_report_json(results, REPORT_DIR)

    kg.close()