# -*- coding: utf-8 -*-
"""metrics.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xBTowjo6CrqmvKIwq8rFbK5B3ZFJQUoD
"""

import numpy as np

def calculate_ranking_metrics(ranked_hypotheses, k=3):
    """
    Calculates nDCG@k and MRR for the ranked list of hypotheses.

    Assumption:
    - Relevance = 1 if the hypothesis has ANY supporting literature (ne_hits > 0 or nc_hits > 0).
    - Relevance = 0 if it is completely novel (no direct evidence found).
    """
    if not ranked_hypotheses:
        return 0.0, 0.0

    # 1. Define Relevance Scores (Binary: 1 = Supported, 0 = Novel/Unsupported)
    # You can also use 'ranking_score' if you want to evaluate against the model's own score,
    # but typically you evaluate against EXTERNAL truth (literature hits).
    relevance = []
    for h in ranked_hypotheses:
        # Check if the validator found exact (ne) or contextual (nc) PubMed hits
        if h.get('ne_hits', 0) > 0 or h.get('nc_hits', 0) > 0:
            relevance.append(1)
        else:
            relevance.append(0)

    # --- Metric 1: Mean Reciprocal Rank (MRR) ---
    # Score is 1/rank of the *first* relevant item found.
    mrr = 0.0
    for i, rel in enumerate(relevance):
        if rel == 1:
            mrr = 1.0 / (i + 1)
            break

    # --- Metric 2: nDCG@k ---
    def get_dcg(scores):
        # DCG formula: sum( rel_i / log2(i + 2) )
        return sum(r / np.log2(idx + 2) for idx, r in enumerate(scores))

    # Slice list to k (e.g., top 3)
    k = min(k, len(relevance))

    # Calculate DCG for the Actual Ranking
    actual_relevance = relevance[:k]
    dcg = get_dcg(actual_relevance)

    # Calculate DCG for the Ideal Ranking (Sorted Descending)
    ideal_relevance = sorted(relevance, reverse=True)[:k]
    idcg = get_dcg(ideal_relevance)

    # Avoid division by zero
    ndcg = dcg / idcg if idcg > 0 else 0.0

    return mrr, ndcg