# -*- coding: utf-8 -*-
"""synergycheck.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EdlK1FSLI6VNGNJIsd089XUze8d56th7
"""

import os
import pandas as pd

class SynergyChecker:
    def __init__(self, kg, SAVE_PATH="/content/drive/MyDrive/Colab Notebooks/AIcoS/FINAL/data_cache/"):
        self.kg = kg
        self.SAVE_PATH = SAVE_PATH

    def get_drug_synonyms(self, drug_name):
        query = """
        MATCH (d:Drug)
        WHERE d.name = $name
        OPTIONAL MATCH (d)-[:HAS_SYNONYM]->(s:Synonym)
        RETURN d.name AS input_name, collect(s.name) AS synonyms
        """
        with self.kg.driver.session() as session:
            result = session.run(query, name=drug_name).single()
            if result:
                # Combines the input name with the list of synonyms
                return [result["input_name"]] + result["synonyms"]
            return [drug_name] # Returns the input name if drug not found in graph

    def check_drugcomb_synergy(self, drug1, drug2, drugcomb_cache_file="drugcomb_scored.csv"):
        """
        Fetches DrugComb data and summarizes synergy per Cell Line.
        """
        drug1_synonyms = self.get_drug_synonyms(drug1)
        drug2_synonyms = self.get_drug_synonyms(drug2)

        d1_set = {s.lower() for s in drug1_synonyms}
        d2_set = {s.lower() for s in drug2_synonyms}

        # filepath = self.SAVE_PATH + drugcomb_cache_file
        filepath = os.path.join(self.SAVE_PATH, drugcomb_cache_file)

        # Load Data (assuming cache_file exists or logic from previous step)
        if not os.path.exists(filepath):
            print(f"Cache file not found at {filepath}. Downloading...")
            scored_url = "http://drugcombdb.denglab.org/download/drugcombs_scored.csv"
            # response_url = "http://drugcombdb.denglab.org/download/drugcombs_response.csv"

            try:
                df_scored = pd.read_csv(scored_url)
                df_scored.to_csv(filepath, index=False)

            except Exception as e:
                print(f"❌ Error reading file: {e}")

        matches = []
        # Using chunksize for memory efficiency
        for chunk in pd.read_csv(filepath, chunksize=50000):
            mask = (
                (chunk['Drug1'].str.lower().isin(d1_set) & chunk['Drug2'].str.lower().isin(d2_set)) |
                (chunk['Drug1'].str.lower().isin(d2_set) & chunk['Drug2'].str.lower().isin(d1_set))
            )
            matches.append(chunk[mask])

        df = pd.concat(matches)
        if df.empty:
          # print(f"No synergy data found for {drug1} + {drug2}.")
          return

        # Formula: Average of ZIP, Bliss, Loewe, and HSA
        df['consensus_score'] = df[['ZIP', 'Bliss', 'Loewe', 'HSA']].mean(axis=1)

        # 4. Aggregate by Cell Line
        # This keeps the cancer-specific context intact
        summary = df.groupby('Cell line').agg({
            'ZIP': 'mean',
            'Bliss': 'mean',
            'Loewe': 'mean',
            'HSA': 'mean',
            'consensus_score': 'mean'
        }).sort_values(by='consensus_score', ascending=False)

        best_cell_line_name = summary['consensus_score'].idxmax()
        worst_cell_line_name = summary['consensus_score'].idxmin()

        best = summary.loc[best_cell_line_name]
        worst = summary.loc[worst_cell_line_name]

        summary_msg = (
            f"The given drug combination {drug1_synonyms[0]} + {drug2_synonyms[0]} has highest synergy score "
            f"[ZIP: {best['ZIP']:.2f}, Bliss: {best['Bliss']:.2f}, "
            f"Loewe: {best['Loewe']:.2f}, HSA: {best['HSA']:.2f}, "
            f"Consensus: {best['consensus_score']:.2f}] in cell line {best_cell_line_name} "
            f"and lowest synergy score "
            f"[ZIP: {worst['ZIP']:.2f}, Bliss: {worst['Bliss']:.2f}, "
            f"Loewe: {worst['Loewe']:.2f}, HSA: {worst['HSA']:.2f}, "
            f"Consensus: {worst['consensus_score']:.2f}] in cell line {worst_cell_line_name}."
        )

        return summary_msg

